/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class RectangleTest {
  //testing if its creating an instance of the rectangle class
    @Test
    public void newRectangle_instantiatesCorrectly(){
      Rectangle testRectangle = new Rectangle(2,4);
      assertEquals(true, testRectangle instanceof Rectangle );
    }
    //test for saving length
    @Test
    public void newRectangle_getsLength_2(){
      Rectangle testRectangle = new Rectangle(2,4);
      assertEquals(2, testRectangle.getLength());
    }
    //test for saving width
    @Test
    public void newRectangle_getsWidth_4(){
      Rectangle testRectangle = new Rectangle(2,4);
      assertEquals(4, testRectangle.getWidth());
    }
    //test if rectangle is not a square
    @Test
    public void isSquare_whenNotSquare_false(){
      Rectangle testRectangle = new Rectangle(2,4);
      assertEquals(false, testRectangle.isSquare());
    }
    //test if rectangle is a square
    @Test
    public void isSquare_allSidesEqual_true(){
      Rectangle testRectangle = new Rectangle(2,2);
      assertEquals(true, testRectangle.isSquare());
    }

}
